<?php
session_start();
require_once 'db.php';
require_once 'nepali_date.php';
require_once 'partials/app_layout.php';
if (!isset($_SESSION['user_id'])) { header('Location: login.php'); exit(); }
$user_id=(int)$_SESSION['user_id']; $userName=$_SESSION['name']??'User'; $profilePhoto=$_SESSION['profile_photo']??'default.png'; $joinedBs=$_SESSION['joined_date_bs']??'';
$today_bs=NepaliDateConverter::todayBs(); $bsMonth=substr($today_bs,0,7);
function mny($n){return 'NPR '.number_format((float)$n,2);} function eh($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$types=['starting_balance'=>'Opening Balance','income'=>'Income / Profit','expense'=>'Expenses','lend'=>'Lend','lend_repayment'=>'Lend Recovered','borrow'=>'Borrow','borrow_repayment'=>'Borrow Repaid','investment'=>'Investment','investment_sell'=>'Share Sell','loss'=>'Share / Trading Loss','bad_debt'=>'Bad Debt','ssf'=>'SSF / Long Term'];
function totals($conn,$uid,$condition='1=1'){$q=$conn->prepare("SELECT transaction_type,COALESCE(SUM(amount),0) total,COUNT(*) cnt FROM transactions WHERE user_id=? AND ($condition) GROUP BY transaction_type");$q->bind_param('i',$uid);$q->execute();$r=$q->get_result();$a=[];while($x=$r->fetch_assoc())$a[$x['transaction_type']]=['total'=>(float)$x['total'],'cnt'=>(int)$x['cnt'];return $a;}
function tv($a,$keys){$n=0;foreach($keys as $k)$n+=(float)($a[$k]['total']??0);return $n;}
$life=totals($conn,$user_id); $safeMonth=$conn->real_escape_string($bsMonth); $month=totals($conn,$user_id,"date_bs LIKE '{$safeMonth}-%'");
$opening=tv($life,['starting_balance']);$income=tv($life,['income']);$expense=tv($life,['expense']);$lend=tv($life,['lend']);$lendRep=tv($life,['lend_repayment']);$borrow=tv($life,['borrow']);$borrowRep=tv($life,['borrow_repayment']);$loss=tv($life,['loss','bad_debt']);
$netLend=max(0,$lend-$lendRep-$life['bad_debt']['total']??0); $netBorrow=max(0,$borrow-$borrowRep);
$cashQ=$conn->prepare("SELECT payment_method,SUM(CASE WHEN transaction_type IN ('starting_balance','income','lend_repayment','borrow','investment_sell') THEN amount WHEN transaction_type IN ('expense','lend','borrow_repayment','investment','loss','bad_debt','ssf') THEN -amount ELSE 0 END) bal FROM transactions WHERE user_id=? GROUP BY payment_method");$cashQ->bind_param('i',$user_id);$cashQ->execute();$cr=$cashQ->get_result();$bank=0;$hand=0;while($x=$cr->fetch_assoc()){if(in_array(strtolower(trim($x['payment_method']??'')),['cash','hand_cash']))$hand+=(float)$x['bal'];else $bank+=(float)$x['bal'];}$liquid=$bank+$hand;
$invQ=$conn->prepare("SELECT investment_type,COALESCE(SUM(amount),0) total FROM transactions WHERE user_id=? AND transaction_type='investment' AND (status IS NULL OR status!='settled') GROUP BY investment_type");$invQ->bind_param('i',$user_id);$invQ->execute();$ir=$invQ->get_result();$long=0;$short=0;while($x=$ir->fetch_assoc()){if(in_array(strtolower(trim($x['investment_type']??'')),['sip','sip_long_term','ssf','ssf_fund']))$long+=(float)$x['total'];else $short+=(float)$x['total'];}$invest=$long+$short;
$mi=tv($month,['income']);$me=tv($month,['expense']);$ml=tv($month,['lend']);$mb=tv($month,['borrow']);$mrepL=tv($month,['lend_repayment']);$mrepB=tv($month,['borrow_repayment']);$minv=tv($month,['investment','ssf']);$msell=tv($month,['investment_sell']);$mloss=tv($month,['loss','bad_debt']);$mout=$me+$ml+$mrepB+$minv+$mloss;$mnet=$mi+$mb+$mrepL+$msell-$mout;$save=$mi>0?max(0,min(100,(($mi-$me)/$mi)*100)):0;
$topicQ=$conn->prepare("SELECT transaction_type,COALESCE(NULLIF(TRIM(subject),''),'Uncategorized') topic,SUM(amount) total,COUNT(*) cnt FROM transactions WHERE user_id=? AND date_bs LIKE ? GROUP BY transaction_type,topic ORDER BY total DESC");$pat=$bsMonth.'-%';$topicQ->bind_param('is',$user_id,$pat);$topicQ->execute();$topics=$topicQ->get_result();
renderAppHead('Personal Finance Dashboard');renderAppHeader($userName,$profilePhoto,$joinedBs,$today_bs);
?>
<style>
:root{--bg:#f5f7fb;--card:#fff;--text:#0f172a;--muted:#64748b;--line:#e5eaf0;--blue:#2563eb;--green:#16a34a;--red:#dc2626;--amber:#d97706;--purple:#7c3aed}body{background:var(--bg)}.dash{max-width:900px;margin:auto;padding:8px 12px 105px}.hero{background:linear-gradient(135deg,#0b1220,#1e293b);color:#fff;border-radius:22px;padding:20px;box-shadow:0 12px 28px rgba(15,23,42,.18);margin-bottom:15px}.ey{font-size:10px;color:#93c5fd;font-weight:800;text-transform:uppercase;letter-spacing:.7px}.bal{font:900 27px ui-monospace,monospace;margin:5px 0}.hero-sub{font-size:10px;color:#cbd5e1}.kpis{display:grid;grid-template-columns:1fr 1fr;gap:10px;border-top:1px solid #334155;padding-top:13px;margin-top:15px}.kpi span{display:block;font-size:8px;color:#94a3b8;font-weight:800;text-transform:uppercase}.kpi b{display:block;font:800 13px ui-monospace,monospace;margin-top:2px}.section{display:flex;justify-content:space-between;align-items:center;margin:18px 1px 9px}.section h2{font-size:14px;margin:0;font-weight:850}.section small{font-size:9px;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:13px;min-height:78px}.card span{display:block;font-size:9px;color:var(--muted);font-weight:750}.card b{display:block;font:800 13px ui-monospace,monospace;margin-top:5px}.blue{color:var(--blue)}.green{color:var(--green)}.red{color:var(--red)}.amber{color:var(--amber)}.purple{color:var(--purple)}.month{background:#fff;border:1px solid var(--line);border-radius:18px;padding:14px}.monthtop{display:flex;justify-content:space-between;align-items:flex-end}.monthtop small{font-size:9px;color:var(--muted)}.monthtop strong{font-size:16px}.bar{height:8px;background:#edf1f5;border-radius:20px;overflow:hidden;margin:10px 0}.bar i{display:block;height:100%;width:<?=$save?>%;background:linear-gradient(90deg,#2563eb,#16a34a)}.tiny{display:flex;justify-content:space-between;font-size:9px;color:var(--muted)}.topic{background:#fff;border:1px solid var(--line);border-radius:17px;overflow:hidden}.topicrow{display:flex;align-items:center;gap:9px;padding:11px 12px;border-bottom:1px solid #f0f3f6}.topicrow:last-child{border:0}.dot{width:32px;height:32px;border-radius:10px;background:#eff6ff;display:grid;place-items:center;font-size:14px}.topicmain{flex:1;min-width:0}.topicmain strong{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.topicmain small{font-size:9px;color:#94a3b8}.amt{text-align:right;font:800 10px ui-monospace,monospace}.pill{display:inline-block;background:#f1f5f9;border-radius:6px;padding:2px 5px;font:800 7px system-ui;color:#475569;margin-top:2px}.note{background:#fff;border:1px solid var(--line);border-radius:17px;padding:13px;font-size:10px;color:var(--muted);line-height:1.5}@media(min-width:650px){.grid{grid-template-columns:repeat(4,1fr)}.kpis{grid-template-columns:repeat(4,1fr)}}
</style>
<div class="dash">
<section class="hero"><div class="ey">Total available cash</div><div class="bal"><?=mny($liquid)?></div><div class="hero-sub">Bank / Digital: <?=mny($bank)?> &nbsp;•&nbsp; Hand Cash: <?=mny($hand)?></div><div class="kpis"><div class="kpi"><span>Total Investments</span><b style="color:#38bdf8"><?=mny($invest)?></b></div><div class="kpi"><span>Total Expenses</span><b style="color:#f87171"><?=mny($expense)?></b></div><div class="kpi"><span>Net Lend</span><b style="color:#4ade80"><?=mny($netLend)?></b></div><div class="kpi"><span>Net Borrow</span><b style="color:#fbbf24"><?=mny($netBorrow)?></b></div></div></section>
<div class="section"><h2>Cash & investment position</h2><small>Current balances</small></div><div class="grid"><div class="card"><span>Bank + digital wallets</span><b class="blue"><?=mny($bank)?></b></div><div class="card"><span>Hand cash</span><b class="green"><?=mny($hand)?></b></div><div class="card"><span>Short-term / trading</span><b class="purple"><?=mny($short)?></b></div><div class="card"><span>Long-term / SIP / SSF</span><b class="blue"><?=mny($long)?></b></div></div>
<div class="section"><h2>BS <?=eh($bsMonth)?> monthly summary</h2><small>Today <?=eh($today_bs)?></small></div><section class="month"><div class="monthtop"><div><small>Income / profit</small><br><strong class="green">+<?=mny($mi)?></strong></div><div style="text-align:right"><small>Net movement</small><br><strong class="<?=($mnet>=0?'green':'red')?>"><?=mny($mnet)?></strong></div></div><div class="bar"><i></i></div><div class="tiny"><span>Income retained <?=number_format($save,0)?>%</span><span>Outflow <?=mny($mout)?></span></div></section>
<div class="grid" style="margin-top:8px"><div class="card"><span>Income / profit</span><b class="green"><?=mny($mi)?></b></div><div class="card"><span>Expenses</span><b class="red"><?=mny($me)?></b></div><div class="card"><span>Lend</span><b class="amber"><?=mny($ml)?></b></div><div class="card"><span>Borrow</span><b class="amber"><?=mny($mb)?></b></div><div class="card"><span>Investments</span><b class="purple"><?=mny($minv)?></b></div><div class="card"><span>Share sell return</span><b class="green"><?=mny($msell)?></b></div><div class="card"><span>Share / trading loss</span><b class="red"><?=mny($mloss)?></b></div><div class="card"><span>Repayments</span><b><?=mny($mrepL+$mrepB)?></b></div></div>
<div class="section"><h2>Every main transaction & topic</h2><small>BS <?=eh($bsMonth)?></small></div><section class="topic"><?php if($topics->num_rows):while($r=$topics->fetch_assoc()):?><div class="topicrow"><div class="dot"><?=isset($types[$r['transaction_type']])?'•':'•'?></div><div class="topicmain"><strong><?=eh($r['topic'])?></strong><small><?=eh($types[$r['transaction_type']]??ucfirst(str_replace('_',' ',$r['transaction_type'])))?> • <?=$r['cnt']?> entr<?=((int)$r['cnt']===1?'y':'ies')?></small></div><div class="amt"><?=mny($r['total'])?><br><span class="pill"><?=eh(strtoupper(str_replace('_',' ',$r['transaction_type'])))?></span></div></div><?php endwhile;else:?><div style="padding:20px;text-align:center;color:#94a3b8;font-size:10px">No transactions recorded in this BS month.</div><?php endif;?></section>
<div class="section"><h2>Lifetime totals</h2><a href="reports.php" style="font-size:10px;color:#2563eb;text-decoration:none;font-weight:800">Detailed reports →</a></div><div class="grid"><div class="card"><span>Opening capital</span><b><?=mny($opening)?></b></div><div class="card"><span>Total income</span><b class="green"><?=mny($income)?></b></div><div class="card"><span>Total expenses</span><b class="red"><?=mny($expense)?></b></div><div class="card"><span>Net lend</span><b class="green"><?=mny($netLend)?></b></div><div class="card"><span>Net borrow</span><b class="amber"><?=mny($netBorrow)?></b></div><div class="card"><span>Share / bad-debt loss</span><b class="red"><?=mny($loss)?></b></div></div>
<div class="section"><h2>How balances are calculated</h2></div><div class="note">Available cash = opening balance + income + lend recovery + borrow + share-sale return − expenses − money lent − borrow repayments − investments − realized losses. Net lend subtracts recoveries and bad debt. Net borrow subtracts repayments. Active investments are separated into short-term/trading and long-term/SIP/SSF.</div>
</div>