<?php
session_start();require_once 'db.php';require_once 'nepali_date.php';require_once 'partials/app_layout.php';
if(!isset($_SESSION['user_id'])){header('Location: login.php');exit();}$uid=(int)$_SESSION['user_id'];$today=NepaliDateConverter::todayBs();$defaultMonth=substr($today,0,7);
$period=$_GET['period']??'current';$type=$_GET['type']??'all';$search=trim($_GET['q']??'');$types=['all'=>'All types','starting_balance'=>'Opening','income'=>'Income','expense'=>'Expense','lend'=>'Lend','lend_repayment'=>'Lend recovery','borrow'=>'Borrow','borrow_repayment'=>'Borrow repayment','investment'=>'Investment','investment_sell'=>'Share sell','loss'=>'Share loss','bad_debt'=>'Bad debt','ssf'=>'SSF'];
if(!isset($types[$type]))$type='all';$where='user_id=?';$params=[$uid];$sig='i';if($period==='current'){$where.=" AND date_bs LIKE ?";$params[]=$defaultMonth.'-%';$sig.='s';}elseif(preg_match('/^20[0-9]{2}-((0[1-9])|(1[0-2]))$/',$period)){$where.=" AND date_bs LIKE ?";$params[]=$period.'-%';$sig.='s';}if($type!=='all'){$where.=' AND transaction_type=?';$params[]=$type;$sig.='s';}if($search!==''){$where.=' AND (subject LIKE ? OR party_name LIKE ? OR notes LIKE ?)';$q='%'.$search.'%';$params[]=$q;$params[]=$q;$params[]=$q;$sig.='sss';}
$sql="SELECT * FROM transactions WHERE $where ORDER BY date_ad DESC,id DESC";$stmt=$conn->prepare($sql);$stmt->bind_param($sig,...$params);$stmt->execute();$rows=$stmt->get_result();
$sumQ=$conn->prepare("SELECT COUNT(*) cnt,COALESCE(SUM(amount),0) total,COALESCE(SUM(CASE WHEN transaction_type IN ('income','borrow','lend_repayment','investment_sell','starting_balance') THEN amount ELSE 0 END),0) inflow,COALESCE(SUM(CASE WHEN transaction_type IN ('expense','lend','borrow_repayment','investment','loss','bad_debt','ssf') THEN amount ELSE 0 END),0) outflow FROM transactions WHERE $where");$sumQ->bind_param($sig,...$params);$sumQ->execute();$sum=$sumQ->get_result()->fetch_assoc();$net=(float)$sum['inflow']-(float)$sum['outflow'];
renderAppHead('Transaction Ledger');renderAppHeader($_SESSION['name']??'User',$_SESSION['profile_photo']??'default.png',$_SESSION['joined_date_bs']??'', $today);
?>
<style>:root{--bg:#f5f7fb;--card:#fff;--text:#0f172a;--muted:#64748b;--line:#e5eaf0;--blue:#2563eb;--green:#16a34a;--red:#dc2626;--amber:#d97706;--purple:#7c3aed}body{background:var(--bg)}.ledger{max-width:900px;margin:auto;padding:8px 12px 105px}.filters{background:#fff;border:1px solid var(--line);border-radius:17px;padding:11px;display:grid;grid-template-columns:1fr 1fr;gap:8px}.filters input,.filters select,.filters button{width:100%;border:1px solid #dce2e9;border-radius:10px;background:#f8fafc;padding:10px;font-size:10px;color:var(--text);outline:0}.filters button{background:var(--text);color:#fff;font-weight:800}.search{grid-column:1/-1}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:9px}.metric{background:#fff;border:1px solid var(--line);border-radius:14px;padding:11px}.metric span{display:block;font-size:8px;color:var(--muted);font-weight:800;text-transform:uppercase}.metric b{display:block;font:800 11px ui-monospace,monospace;margin-top:4px}.green{color:var(--green)}.red{color:var(--red)}.blue{color:var(--blue)}.cards{margin-top:9px;background:#fff;border:1px solid var(--line);border-radius:17px;overflow:hidden}.tx{display:grid;grid-template-columns:35px 1fr auto;gap:9px;align-items:center;padding:11px 12px;border-bottom:1px solid #f0f3f6}.tx:last-child{border:0}.ico{width:32px;height:32px;border-radius:10px;background:#eff6ff;display:grid;place-items:center;font-size:13px}.main{min-width:0}.main strong{font-size:11px;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.main small{font-size:8px;color:#94a3b8;display:block;margin-top:3px;line-height:1.4}.right{text-align:right}.right strong{font:800 10px ui-monospace,monospace}.badge{display:inline-block;padding:3px 5px;border-radius:6px;background:#f1f5f9;color:#475569;font-size:7px;font-weight:850;margin-top:3px}.empty{text-align:center;padding:28px;color:#94a3b8;font-size:10px}.topline{display:flex;justify-content:space-between;align-items:center;margin:17px 1px 8px}.topline h2{font-size:14px;margin:0}.topline span{font-size:9px;color:var(--muted)}@media(min-width:650px){.filters{grid-template-columns:1fr 1fr 1fr}.search{grid-column:auto}.summary{grid-template-columns:repeat(3,1fr)}}@media(max-width:370px){.summary{grid-template-columns:1fr}.tx{grid-template-columns:32px 1fr auto}.right strong{font-size:9px}}</style>
<div class="ledger">
<form class="filters" method="get"><select name="period"><option value="current" <?=$period==='current'?'selected':''?>>Current BS month (<?=$defaultMonth?>)</option><?php for($y=(int)substr($defaultMonth,0,4);$y>=$y-4;$y--):for($mo=12;$mo>=1;$mo--):$v=sprintf('%04d-%02d',$y,$mo);?><option value="<?=$v?>" <?=$period===$v?'selected':''?>><?=$v?> BS</option><?php endfor;endfor;?></select><select name="type"><?php foreach($types as $k=>$v):?><option value="<?=esc($k)?>" <?=$type===$k?'selected':''?>><?=esc($v)?></option><?php endforeach;?></select><button type="submit">Filter ledger</button><input class="search" type="search" name="q" value="<?=htmlspecialchars($search)?>" placeholder="Search topic, person, note..."></form>
<div class="summary"><div class="metric"><span>Entries</span><b><?=number_format((int)$sum['cnt'])?></b></div><div class="metric"><span>Inflow</span><b class="green"><?=npr($sum['inflow'])?></b></div><div class="metric"><span>Outflow / net</span><b class="<?=($net>=0?'blue':'red')?>"><?=npr($net)?></b></div></div>
<div class="topline"><h2>Transaction history</h2><span>BS <?=esc($period==='current'?$defaultMonth:$period)?></span></div><section class="cards"><?php $icons=['starting_balance'=>'◉','income'=>'↗','expense'=>'↘','lend'=>'→','lend_repayment'=>'↩','borrow'=>'←','borrow_repayment'=>'↪','investment'=>'◆','investment_sell'=>'◇','loss'=>'!','bad_debt'=>'!','ssf'=>'◆'];if($rows->num_rows):while($r=$rows->fetch_assoc()):$out=in_array($r['transaction_type'],['expense','lend','borrow_repayment','investment','loss','bad_debt','ssf']);$label=$types[$r['transaction_type']]??ucfirst(str_replace('_',' ',$r['transaction_type']));?><article class="tx"><div class="ico"><?=esc($icons[$r['transaction_type']]??'•')?></div><div class="main"><strong><?=esc($r['subject']?:$label)?></strong><small><?=esc($r['date_bs'])?> BS<?php if(!empty($r['party_name'])):?> • <?=esc($r['party_name'])?><?php endif;?><?php if(!empty($r['notes'])):?> • <?=esc($r['notes'])?><?php endif;?></small></div><div class="right"><strong class="<?= $out?'red':'green' ?>"><?=$out?'−':'+'?><?=npr($r['amount'])?></strong><br><span class="badge"><?=esc($label)?></span></div></article><?php endwhile;else:?><div class="empty">No transactions match these filters.</div><?php endif;?></section>
</div>