<?php
session_start();require_once 'db.php';require_once 'nepali_date.php';require_once 'partials/app_layout.php';
if(!isset($_SESSION['user_id'])){header('Location: login.php');exit();}$uid=(int)$_SESSION['user_id'];$today=NepaliDateConverter::todayBs();
$selected=$_GET['month']??substr($today,0,7);if(!preg_match('/^20[0-9]{2}-((0[1-9])|(1[0-2]))$/',$selected))$selected=substr($today,0,7);
$year=substr($selected,0,4);$month=substr($selected,5,2);$like=$selected.'-%';function npr($n){return 'NPR '.number_format((float)$n,2);}function esc($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
function typeTotals($conn,$uid,$where,$param){$q=$conn->prepare("SELECT transaction_type,SUM(amount) total,COUNT(*) cnt FROM transactions WHERE user_id=? AND date_bs LIKE ? GROUP BY transaction_type ORDER BY total DESC");$q->bind_param('is',$uid,$param);$q->execute();$r=$q->get_result();$a=[];while($x=$r->fetch_assoc())$a[$x['transaction_type']]=['total'=>(float)$x['total'],'cnt'=>(int)$x['cnt']];return $a;}
$m=typeTotals($conn,$uid,'date_bs LIKE ?',$like);
$keys=['starting_balance','income','expense','lend','lend_repayment','borrow','borrow_repayment','investment','investment_sell','loss','bad_debt','ssf'];$T=[];foreach($keys as $k)$T[$k]=(float)($m[$k]['total']??0);
$cashOut=$T['expense']+$T['lend']+$T['borrow_repayment']+$T['investment']+$T['loss']+$T['bad_debt']+$T['ssf'];$cashIn=$T['starting_balance']+$T['income']+$T['lend_repayment']+$T['borrow']+$T['investment_sell'];$net=$cashIn-$cashOut;
$topicQ=$conn->prepare("SELECT transaction_type,COALESCE(NULLIF(TRIM(subject),''),'Uncategorized') topic,SUM(amount) total,COUNT(*) cnt FROM transactions WHERE user_id=? AND date_bs LIKE ? GROUP BY transaction_type,topic ORDER BY total DESC");$topicQ->bind_param('is',$uid,$like);$topicQ->execute();$topics=$topicQ->get_result();
$dayQ=$conn->prepare("SELECT date_bs,SUM(CASE WHEN transaction_type IN ('income','borrow','lend_repayment','investment_sell','starting_balance') THEN amount ELSE 0 END) inflow,SUM(CASE WHEN transaction_type IN ('expense','lend','borrow_repayment','investment','loss','bad_debt','ssf') THEN amount ELSE 0 END) outflow,COUNT(*) cnt FROM transactions WHERE user_id=? AND date_bs LIKE ? GROUP BY date_bs ORDER BY date_bs");$dayQ->bind_param('is',$uid,$like);$dayQ->execute();$days=$dayQ->get_result();
$lifeQ=$conn->prepare("SELECT transaction_type,SUM(amount) total FROM transactions WHERE user_id=? GROUP BY transaction_type");$lifeQ->bind_param('i',$uid);$lifeQ->execute();$lifeR=$lifeQ->get_result();$life=[];while($x=$lifeR->fetch_assoc())$life[$x['transaction_type']]=(float)$x['total'];
$invQ=$conn->prepare("SELECT investment_type,SUM(amount) total FROM transactions WHERE user_id=? AND transaction_type='investment' AND (status IS NULL OR status!='settled') GROUP BY investment_type");$invQ->bind_param('i',$uid);$invQ->execute();$invR=$invQ->get_result();$long=0;$short=0;while($x=$invR->fetch_assoc()){if(in_array(strtolower(trim($x['investment_type']??'')),['sip','sip_long_term','ssf','ssf_fund']))$long+=(float)$x['total'];else $short+=(float)$x['total'];}$activeInvest=$long+$short;
renderAppHead('BS Monthly Financial Reports');renderAppHeader($_SESSION['name']??'User',$_SESSION['profile_photo']??'default.png',$_SESSION['joined_date_bs']??'', $today);
?>
<style>:root{--bg:#f5f7fb;--card:#fff;--text:#0f172a;--muted:#64748b;--line:#e5eaf0;--blue:#2563eb;--green:#16a34a;--red:#dc2626;--amber:#d97706;--purple:#7c3aed}body{background:var(--bg)}.report{max-width:900px;margin:auto;padding:8px 12px 105px}.selector{background:#fff;border:1px solid var(--line);border-radius:16px;padding:12px;display:flex;gap:8px;align-items:center}.selector label{font-size:9px;font-weight:800;color:var(--muted)}select,.btn{border:1px solid #dce2e9;border-radius:10px;background:#f8fafc;padding:10px;font-weight:750;font-size:11px;color:var(--text)}.btn{background:var(--text);color:#fff;text-decoration:none}.hero{margin-top:10px;background:linear-gradient(135deg,#0b1220,#1e293b);color:#fff;border-radius:20px;padding:18px}.hero small{color:#93c5fd;font-size:9px;font-weight:800;text-transform:uppercase}.hero h1{font:900 25px ui-monospace,monospace;margin:4px 0}.hero p{font-size:9px;color:#cbd5e1;margin:0}.kpis{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px;border-top:1px solid #334155;padding-top:12px}.kpi span{display:block;font-size:8px;color:#94a3b8;font-weight:800;text-transform:uppercase}.kpi b{font:800 12px ui-monospace,monospace;display:block;margin-top:3px}.section{display:flex;justify-content:space-between;align-items:center;margin:18px 1px 9px}.section h2{font-size:14px;margin:0}.section small{font-size:9px;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.card{background:#fff;border:1px solid var(--line);border-radius:15px;padding:12px}.card span{display:block;font-size:9px;color:var(--muted);font-weight:750}.card b{display:block;font:800 12px ui-monospace,monospace;margin-top:5px}.green{color:var(--green)}.red{color:var(--red)}.amber{color:var(--amber)}.purple{color:var(--purple)}.blue{color:var(--blue)}.tablebox{background:#fff;border:1px solid var(--line);border-radius:16px;overflow:hidden}.row{display:grid;grid-template-columns:1.3fr .7fr .8fr;padding:10px 11px;border-bottom:1px solid #f0f3f6;font-size:10px;align-items:center}.row:last-child{border:0}.head{background:#f8fafc;font-size:8px;font-weight:850;text-transform:uppercase;color:var(--muted)}.right{text-align:right}.badge{display:inline-block;background:#eef2f7;border-radius:6px;padding:3px 5px;font-size:7px;font-weight:850;color:#475569;margin-top:2px}.empty{text-align:center;padding:22px;color:#94a3b8;font-size:10px}@media(min-width:650px){.grid{grid-template-columns:repeat(4,1fr)}.kpis{grid-template-columns:repeat(4,1fr)}}</style>
<div class="report">
<form class="selector" method="get"><label>BS MONTH</label><select name="month"><option value="<?=$selected?>"><?=$selected?> BS</option><?php for($y=(int)$year;$y>=(int)$year-4;$y--):for($mo=12;$mo>=1;$mo--):$v=sprintf('%04d-%02d',$y,$mo);?><option value="<?=$v?>" <?=$v===$selected?'selected':''?>><?=$v?> BS</option><?php endfor;endfor;?></select><button class="btn" type="submit">Apply</button><a class="btn" href="reports.php">Current</a></form>
<section class="hero"><small>Monthly financial position</small><h1><?=npr($net)?></h1><p>BS <?=$selected?> • Current date <?=esc($today)?> • Inflow <?=npr($cashIn)?> • Outflow <?=npr($cashOut)?></p><div class="kpis"><div class="kpi"><span>Income / Profit</span><b style="color:#4ade80"><?=npr($T['income'])?></b></div><div class="kpi"><span>Expenses</span><b style="color:#f87171"><?=npr($T['expense'])?></b></div><div class="kpi"><span>Investments</span><b style="color:#c084fc"><?=npr($T['investment']+$T['ssf'])?></b></div><div class="kpi"><span>Share Sell</span><b style="color:#4ade80"><?=npr($T['investment_sell'])?></b></div></div></section>
<div class="section"><h2>All main transaction categories</h2><small>Selected BS month</small></div><div class="grid"><div class="card"><span>Opening balance</span><b><?=npr($T['starting_balance'])?></b></div><div class="card"><span>Income / profit</span><b class="green"><?=npr($T['income'])?></b></div><div class="card"><span>Expenses</span><b class="red"><?=npr($T['expense'])?></b></div><div class="card"><span>Lend</span><b class="amber"><?=npr($T['lend'])?></b></div><div class="card"><span>Lend recovered</span><b class="green"><?=npr($T['lend_repayment'])?></b></div><div class="card"><span>Borrow</span><b class="amber"><?=npr($T['borrow'])?></b></div><div class="card"><span>Borrow repaid</span><b class="red"><?=npr($T['borrow_repayment'])?></b></div><div class="card"><span>Investments</span><b class="purple"><?=npr($T['investment'])?></b></div><div class="card"><span>SSF / long term</span><b class="blue"><?=npr($T['ssf'])?></b></div><div class="card"><span>Share sell return</span><b class="green"><?=npr($T['investment_sell'])?></b></div><div class="card"><span>Share / trading loss</span><b class="red"><?=npr($T['loss'])?></b></div><div class="card"><span>Bad debt</span><b class="red"><?=npr($T['bad_debt'])?></b></div></div>
<div class="section"><h2>Every topic / subject</h2><small>Nothing hidden</small></div><section class="tablebox"><div class="row head"><div>Topic</div><div>Type / Entries</div><div class="right">Amount</div></div><?php if($topics->num_rows):while($r=$topics->fetch_assoc()):?><div class="row"><div><strong><?=esc($r['topic'])?></strong></div><div><span class="badge"><?=esc(strtoupper(str_replace('_',' ',$r['transaction_type'])))?></span><br><span style="color:#94a3b8;font-size:8px"><?=$r['cnt']?> entries</span></div><div class="right"><strong><?=npr($r['total'])?></strong></div></div><?php endwhile;else:?><div class="empty">No transactions in this BS month.</div><?php endif;?></section>
<div class="section"><h2>Daily BS activity</h2><small>Monthly trend</small></div><section class="tablebox"><div class="row head"><div>BS Date</div><div>Entries</div><div class="right">Net</div></div><?php if($days->num_rows):while($r=$days->fetch_assoc()):$dn=(float)$r['inflow']-(float)$r['outflow'];?><div class="row"><div><strong><?=esc($r['date_bs'])?></strong></div><div><?=$r['cnt']?></div><div class="right" style="font-weight:800;color:<?=$dn>=0?'var(--green)':'var(--red)'?>"><?=npr($dn)?></div></div><?php endwhile;else:?><div class="empty">No daily activity.</div><?php endif;?></section>
<div class="section"><h2>Current investment position</h2><small>Active / unsettled</small></div><div class="grid"><div class="card"><span>Total active investment</span><b class="purple"><?=npr($activeInvest)?></b></div><div class="card"><span>Short-term / trading</span><b class="purple"><?=npr($short)?></b></div><div class="card"><span>Long-term / SIP / SSF</span><b class="blue"><?=npr($long)?></b></div><div class="card"><span>Realized loss</span><b class="red"><?=npr(($life['loss']??0)+($life['bad_debt']??0))?></b></div></div>
</div>